"""Reproducible baseline and classifier evaluation on a chronological holdout."""
import hashlib
import json
from pathlib import Path
import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from preprocessing import ROOT, CATEGORICAL, NUMERIC, FEATURES, load_dataset, temporal_split


class TransitionBaseline:
    """Most frequent next cell for each current cell, learned only from training."""
    def fit(self, X, y):
        table = pd.DataFrame({"cell": X.current_cell.to_numpy(), "target": list(y)})
        self.fallback = table.target.mode().iloc[0]
        self.mapping = table.groupby("cell").target.agg(lambda s: s.mode().iloc[0]).to_dict()
        return self

    def predict(self, X):
        return X.current_cell.map(self.mapping).fillna(self.fallback).to_numpy()


def make_model(classifier):
    encoder = ColumnTransformer([
        ("categories", OneHotEncoder(handle_unknown="ignore", sparse_output=False), CATEGORICAL),
        ("numeric", "passthrough", NUMERIC)])
    return Pipeline([("features", encoder), ("classifier", classifier)])


def train_project():
    _, visits, examples, stats = load_dataset()
    train, test, cutoff, purged = temporal_split(examples)
    if train.next_cell.nunique() < 2:
        raise ValueError("Training requires at least two destination classes.")
    labels = sorted(examples.next_cell.unique().tolist())
    estimators = {
        "Transition baseline": TransitionBaseline(),
        "Decision Tree": make_model(DecisionTreeClassifier(max_depth=5, min_samples_leaf=3, random_state=42)),
        # Parameters reported for the paper's best model; no tuning on holdout.
        "Gradient Boosting": make_model(GradientBoostingClassifier(
            n_estimators=100, max_depth=9, learning_rate=0.05, random_state=42))}
    report = {"dataset": stats, "cutoff": cutoff.isoformat(), "train_rows": len(train),
              "test_rows": len(test), "purged_rows": purged, "seed": 42,
              "features": FEATURES, "labels": labels, "models": {},
              "demo_model": "Gradient Boosting",
              "selection_policy": "Gradient Boosting fixed in advance from the paper; no test-set selection.",
              "source_sha256": {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                                for p in (ROOT / "data" / "raw").glob("*.csv")}}
    predictions = test[["time", "target_time", "supi", "previous_cell", "current_cell", "next_cell"]].copy()
    for name, model in estimators.items():
        model.fit(train[FEATURES], train.next_cell)
        predicted = model.predict(test[FEATURES])
        report["models"][name] = {
            "accuracy": float(accuracy_score(test.next_cell, predicted)),
            "macro_f1": float(f1_score(test.next_cell, predicted, labels=labels, average="macro", zero_division=0)),
            "confusion_matrix": confusion_matrix(test.next_cell, predicted, labels=labels).tolist(),
            "classification_report": classification_report(test.next_cell, predicted, labels=labels,
                                                          output_dict=True, zero_division=0)}
        predictions[name] = predicted
    (ROOT / "models").mkdir(exist_ok=True)
    (ROOT / "results").mkdir(exist_ok=True)
    # Keep inference artifacts limited to sklearn objects, portable across entry points.
    joblib.dump({"model": estimators["Gradient Boosting"], "cutoff": cutoff,
                 "features": FEATURES, "source_sha256": report["source_sha256"]},
                ROOT / "models" / "gradient_boosting.joblib")
    (ROOT / "results" / "metrics.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    predictions.to_csv(ROOT / "results" / "test_predictions.csv", index=False)
    lines = ["# Measured results", "", "Generated by `python train.py` using the authors' February dataset.", "",
             f"Train: {len(train)} examples. Test: {len(test)} examples. Boundary examples purged: {purged}.",
             f"Chronological cutoff: {cutoff} (source timezone unspecified).", "",
             "| Model | Accuracy | Macro-F1 |", "|---|---:|---:|"]
    for name, result in report["models"].items():
        lines.append(f"| {name} | {result['accuracy']:.2%} | {result['macro_f1']:.4f} |")
    lines.extend(["", "These are this prototype's results, not a reproduction of the paper's 80.65% result.",
                  "Features, session filtering and chronological splitting differ. Devices occur in both splits;",
                  "this evaluates later events for known devices, not generalization to new subscribers.",
                  "The demo uses Gradient Boosting selected in advance from the paper, regardless of test ranking."])
    (ROOT / "results" / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return report


if __name__ == "__main__":
    train_project()
